### ISSUE TITLE
issue 발견

### ISSUE THREAD

**Issue by we4sley** [g0pher98/WIL#2]
<img width="694" alt="KakaoTalk_20210609_013411873" src="https://user-images.githubusercontent.com/77000498/121224346-6c889380-c8c3-11eb-8f8a-74f17045226e.png">

**Comment by g0pher98** [comment]
설명 좀 달아주세요 **King0기**님

**Comment by we4sley** [comment]
> 설명 좀 달아주세요 **King0기**님

ㅋ 공부하닥 피식 웃음

**Comment by g0pher98** [comment]
ㅋㅋㅋㅋ 이슈 왜 단건데

**Comment by graygreat** [comment]
> ㅋㅋㅋㅋ 이슈 왜 단건데

감명 깊었나봄
